const collection = [
    {
        title: "Lion King",
        director: "Rob Minkoff",
        releasedate: "June 24, 1994",
        releasecountry: "USA",
        duration: "1h 27m",
        genres: ["Musical", "Family"],
        cast: ["Jeremy Irons", "James Earl Jones", "Matthew Broderick", "Rowan Atkinson", "Robert Guillaume"],
        thumbnail: "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTzK5hNoRPkiTZdYpWMCiD5J5pwMnLVxnMCKftPXcOj5i0gouCb",
        trailer: "https://www.youtube.com/watch?v=lFzVJEksoDY",
        imdb: "https://www.imdb.com/title/tt0110357/?ref_=nv_sr_srsg_0",
        imdbrating: "8.5/10"
    },
    {
        title: "Her",
        director: "Spike Jonze",
        releasedate: "October 12, 2013",
        releasecountry: "USA",
        duration: "2h 6m",
        genres: ["Romance", "Sci-fi"],
        cast: ["Joaquin Phoenix", "Spike Jonze", "Scarlett Johansson", "Rooney Mara", "Olivia Wilde"],
        thumbnail: "https://m.media-amazon.com/images/M/MV5BMjA1Nzk0OTM2OF5BMl5BanBnXkFtZTgwNjU2NjEwMDE@._V1_.jpg",
        trailer: "https://www.youtube.com/watch?v=dJTU48_yghs",
        imdb: "https://www.imdb.com/title/tt1798709/?ref_=ttmi_tt",
        imdbrating: "8.0/10"
    },
    {
        title: "Fight Club",
        director: "David Fincher",
        releasedate: "September 10, 1999",
        releasecountry: "Venice",
        duration: "2h 19m",
        genres: ["Drama", "Thriller"],
        cast: ["Brad Pitt", "Helena Bonham Carter", "Jared Leto", "Meat Loaf", "Holt McCallany"],
        thumbnail: "https://m.media-amazon.com/images/M/MV5BNDIzNDU0YzEtYzE5Ni00ZjlkLTk5ZjgtNjM3NWE4YzA3Nzk3XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_.jpg",
        trailer: "https://www.youtube.com/watch?v=qtRKdVHc-cE",
        imdb: "https://www.imdb.com/title/tt0137523/?ref_=fn_al_tt_1",
        imdbrating: "8.8/10"
    },
    {
        title: "Peaky Blinders",
        director: "Otto Bathurst",
        releasedate: "September 12, 2013",
        releasecountry: "USA",
        duration: "6 seasons",
        genres: ["Drama", "Crime"],
        cast: ["Cillian Murphy", "Paul Anderson", "Tom Hardy", "Helen McCrory", "Sophie Rundle"],
        thumbnail: "https://m.media-amazon.com/images/M/MV5BZjYzZDgzMmYtYjY5Zi00YTk1LThhMDYtNjFlNzM4MTZhYzgyXkEyXkFqcGdeQXVyMTE5NDQ1MzQ3._V1_.jpg",
        trailer: "https://www.youtube.com/watch?v=oVzVdvGIC7U",
        imdb: "https://www.imdb.com/title/tt2442560/?ref_=nv_sr_srsg_0",
        imdbrating: "8.8/10"
    },
    {
        title: "Black Mirror",
        director: "James Hawes",
        releasedate: "December 4, 2011",
        releasecountry: "UK",
        duration: "5 seasons",
        genres: ["Sci-fi", "Drama"],
        cast: ["Bryce Dallas Howard", "Hayley Atwell", "Michaela Coel", "Jon Hamm", "Anthony Mackie"],
        thumbnail: "https://m.media-amazon.com/images/M/MV5BYTM3YWVhMDMtNjczMy00NGEyLWJhZDctYjNhMTRkNDE0ZTI1XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg",
        trailer: "https://www.youtube.com/watch?v=V0XOApF5nLU",
        imdb: "https://www.imdb.com/title/tt2085059/?ref_=nv_sr_srsg_0",
        imdbrating: "8.8/10"
    },
    {
        title: "The Platform",
        director: "Galder Gaztelu-Urrutia",
        releasedate: "November 8, 2019",
        releasecountry: "Spain",
        duration: "1h 34m",
        genres: ["Thriller", "Horror"],
        cast: ["Alexandra Masangkay", "Iván Massagué", "Zorion Eguileor", "Antonia San Juan", "Zihara Llana"],
        thumbnail: "https://m.media-amazon.com/images/M/MV5BOTMyYTIyM2MtNjQ2ZC00MWFkLThhYjQtMjhjMGZiMjgwYjM2XkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg",
        trailer: "https://www.youtube.com/watch?v=RlfooqeZcdY",
        imdb: "https://www.imdb.com/title/tt8228288/?ref_=nv_sr_srsg_0",
        imdbrating: "7.0/10"
    },
    {
        title: "Doctor Strange",
        director: "Scott Derrickson",
        releasedate: "May 2, 2022",
        releasecountry: "USA",
        duration: "1h 55m",
        genres: ["Action", "Adventure"],
        cast: ["Benedict Cumberbatch", "Benedict Wong", "Rachel McAdams", "Chiwetel Ejiofor", "Tilda Swinton"],
        thumbnail: "https://m.media-amazon.com/images/M/MV5BNjgwNzAzNjk1Nl5BMl5BanBnXkFtZTgwMzQ2NjI1OTE@._V1_.jpg",
        trailer: "https://www.youtube.com/watch?v=h7gvFravm4A",
        imdb: "https://www.imdb.com/title/tt1211837/?ref_=nv_sr_srsg_0",
        imdbrating: "7.5/10"
    }, 
    {
        title: "Thor: Ragnarok",
        director: "Taika Waititi",
        releasedate: "October 10, 2017",
        releasecountry: "USA",
        duration: "2h 10m",
        genres: ["Action", "Sci-fi"],
        cast: ["Cate Blanchett", "Chris Hemsworth", "Jeff Goldblum", "Taika Waititi", "Tessa Thompson"],
        thumbnail: "https://m.media-amazon.com/images/M/MV5BMjMyNDkzMzI1OF5BMl5BanBnXkFtZTgwODcxODg5MjI@._V1_.jpg",
        trailer: "https://www.youtube.com/watch?v=ue80QwXMRHg",
        imdb: "https://www.imdb.com/title/tt3501632/?ref_=nv_sr_srsg_0",
        imdbrating: "7.9/10"
    }, 
    {
        title: "Breaking Bad",
        director: "Vince Gilligan",
        releasedate: "January 20, 2008",
        releasecountry: "USA",
        duration: "5 seasons",
        genres: ["Drama", "Crime"],
        cast: ["Bryan Cranston", "Aaron Paul", "Anna Gun", "Dean Norris", "RJ Mitte"],
        thumbnail: "https://m.media-amazon.com/images/M/MV5BYTU3NWI5OGMtZmZhNy00MjVmLTk1YzAtZjA3ZDA3NzcyNDUxXkEyXkFqcGdeQXVyODY5Njk4Njc@._V1_.jpg",
        trailer: "https://www.youtube.com/watch?v=HhesaQXLuRY",
        imdb: "https://www.imdb.com/title/tt0903747/?ref_=nv_sr_srsg_0",
        imdbrating: "9.5/10"
    }, 
    {
        title: "The Office",
        director: "Randall Einhorn",
        releasedate: "March 24, 2005",
        releasecountry: "USA",
        duration: "9 seasons",
        genres: ["Comedy", "Sitcom"],
        cast: ["Steve Carell", "John Krasinksi", "Jenna Fischer", "Rainn Wilson", "Ellie Kemper"],
        thumbnail: "https://m.media-amazon.com/images/M/MV5BMDNkOTE4NDQtMTNmYi00MWE0LWE4ZTktYTc0NzhhNWIzNzJiXkEyXkFqcGdeQXVyMzQ2MDI5NjU@._V1_.jpg",
        trailer: "https://www.youtube.com/watch?v=tNcDHWpselE",
        imdb: "https://www.imdb.com/title/tt0386676/?ref_=fn_al_tt_1",
        imdbrating: "9.0/10"
    },
    {
        title: "Shameless",
        director: "John Wells",
        releasedate: "January 9, 2011",
        releasecountry: "USA",
        duration: "11 seasons",
        genres: ["Comedy", "Drama"],
        cast: ["Emmy Rossum", "William H. Macy", "Jeremy Allen White", "Cameron Monaghan", "Ethan Cutkosky"],
        thumbnail: "https://m.media-amazon.com/images/M/MV5BZDgxNjQ2MjMtMjk2Yi00M2Q2LWI0ZDktOGM1NWI5YWUzMjk4XkEyXkFqcGdeQXVyOTA3MTMyOTk@._V1_.jpg",
        trailer: "https://www.youtube.com/watch?v=9tvkYS5cA58",
        imdb: "https://www.imdb.com/title/tt1586680/?ref_=nv_sr_srsg_0",
        imdbrating: "8.6/10"
    }, 
    {
        title: "Howl's Moving Castle",
        director: "Hayao Miyazaki",
        releasedate: "5 September 2004",
        releasecountry: "Venice",
        duration: "1h 59m",
        genres: ["Fantasy", "Adventure"],
        cast: ["Christian Bale", "Takuya Kimura", "Chieko Baisho", "Tatsuya Gashuin", "Emily Mortimer"],
        thumbnail: "https://m.media-amazon.com/images/M/MV5BMTY1OTg0MjE3MV5BMl5BanBnXkFtZTcwNTUxMTkyMQ@@._V1_.jpg",
        trailer: "https://www.youtube.com/watch?v=iwROgK94zcM",
        imdb: "https://www.imdb.com/title/tt0347149/?ref_=tt_mv_close",
        imdbrating: "8.2/10"
    },
    {
        title: "Chainsaw Man",
        director: "Ryū Nakayama",
        releasedate: "October 12, 2022",
        releasecountry: "Japan",
        duration: "1 season",
        genres: ["Animation", "Action"],
        cast: ["Kikunosuke Toya", "Tomori Kusunoki", "Fairouz Ai", "Shogo Sakata", "Kenjiro Tsuda"],
        thumbnail: "https://m.media-amazon.com/images/M/MV5BNGFkZDRlNWEtMDdlMy00MGUyLWJhOGMtOTU0MTA2YTM1M2QwXkEyXkFqcGdeQXVyMTUzNjM4ODE1._V1_.jpg",
        trailer: "https://www.youtube.com/watch?v=l96zmDlWCBk",
        imdb: "https://www.imdb.com/title/tt13616990/?ref_=nv_sr_srsg_0",
        imdbrating: "8.6/10"
    },
    {
        title: "WALL-E",
        director: "Andrew Stanton",
        releasedate: "June 23, 2008",
        releasecountry: "USA",
        duration: "1h 43m",
        genres: ["Family", "Adventure"],
        cast: ["Andrew Stanton", "Ben Burtt", "Elissa Knight", "John Ratzenberger", "Jeff Garlin"],
        thumbnail: "https://m.media-amazon.com/images/M/MV5BMjExMTg5OTU0NF5BMl5BanBnXkFtZTcwMjMxMzMzMw@@._V1_.jpg",
        trailer: "https://www.youtube.com/watch?v=3Mi62VKDhm0",
        imdb: "https://www.imdb.com/title/tt0910970/?ref_=fn_al_tt_3",
        imdbrating: "8.4/10"
    }, 
    {
        title: "Big Hero 6",
        director: "Chris Williams",
        releasedate: "October 23, 2014",
        releasecountry: "Japan",
        duration: "1h 42m",
        genres: ["Family", "Adventure"],
        cast: ["Ryan Potter", "Scott Adsit", "Maya Rudolph", "T.J. Miller", "Jamie Chung"],
        thumbnail: "https://m.media-amazon.com/images/M/MV5BMDliOTIzNmUtOTllOC00NDU3LWFiNjYtMGM0NDc1YTMxNjYxXkEyXkFqcGdeQXVyNTM3NzExMDQ@._V1_.jpg",
        trailer: "https://www.youtube.com/watch?v=z3biFxZIJOQ",
        imdb: "https://www.imdb.com/title/tt2245084/?ref_=nv_sr_srsg_0",
        imdbrating: "7.8/10"
    }, 
    {
        title: "Ozark",
        director: "Jason Bateman",
        releasedate: "July 21, 2017",
        releasecountry: "USA",
        duration: "4 seasons",
        genres: ["Crime", "Drama"],
        cast: ["Jason Bateman", "Laura Linney", "Julia Garner", "Sofia Hublitz", "Skylar Gaertner"],
        thumbnail: "https://m.media-amazon.com/images/M/MV5BZDUxMWNlMTUtYTljZS00MTE0LTlkYjktOTU1ODZjYzBhMTk0XkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_.jpg",
        trailer: "https://www.youtube.com/watch?v=5hAXVqrljbs",
        imdb: "https://www.imdb.com/title/tt5071412/?ref_=fn_al_tt_1",
        imdbrating: "8.5/10"
    }
]